# Generated by Django 5.2.15 on 2026-09-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('devices', '0003_remove_measurement_air_quality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='alertrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(choices=[('power', 'Power'), ('energy_total', 'Energy Total'), ('energy_delta', 'Energy Delta'), ('energy_saved', 'Energy Saved'), ('power_energy', 'Power Energy'), ('temperature', 'Temperature'), ('target_temperature', 'Target Temperature'), ('humidity', 'Humidity'), ('filter_usage', 'Filter Usage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', '-created_at'], name='alerts_aler_device__d5e214_idx'),
        ),
    ]
