# Generated by Django 6.0.6 on 2026-07-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(default='B1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.FloatField(verbose_name=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
