# Generated by Django 5.2.15 on 2026-07-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_room_floor_alter_room_area_alter_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('air_conditioner', 'Air Conditioner')], default='air_conditioner', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under maintenance')], default='active', max_length=20)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_operating_state', models.CharField(blank=True, max_length=30)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='rooms.room')),
            ],
            options={
                'ordering': ['room', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('power', models.FloatField(blank=True, help_text='Watts, instantaneous', null=True)),
                ('energy_total', models.FloatField(blank=True, help_text='Wh, cumulative counter', null=True)),
                ('energy_delta', models.FloatField(blank=True, help_text='Wh, since previous reading', null=True)),
                ('voltage', models.FloatField(blank=True, help_text='Volts', null=True)),
                ('current', models.FloatField(blank=True, help_text='Amps', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('target_temperature', models.FloatField(blank=True, help_text='°C, setpoint', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='%', null=True)),
                ('operating_state', models.CharField(blank=True, max_length=30)),
                ('mode', models.CharField(blank=True, max_length=50)),
                ('fan_mode', models.CharField(blank=True, max_length=30)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['room', 'category'], name='devices_dev_room_id_7f795a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['device', '-timestamp'], name='devices_mea_device__9eaa2a_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['timestamp'], name='devices_mea_timesta_f88b2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('device', 'timestamp'), name='unique_device_timestamp'),
        ),
    ]
