# Generated by Django 5.2.15 on 2026-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='location_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='owner_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='presentation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='measurement',
            name='air_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='co2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='defrost',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='eco_mode',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='fan_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='filter_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pm10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pm100',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pm25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sleep_mode',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='swing_mode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='measurement',
            name='wind_free',
            field=models.BooleanField(null=True),
        ),
    ]
