# Generated by Django 5.2.15 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_device_type_device_firmware_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='air_quality',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='co2',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='current',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='defrost',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='eco_mode',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='fan_speed',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='pm10',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='pm100',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='pm25',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='voltage',
        ),
        migrations.AddField(
            model_name='measurement',
            name='energy_saved',
            field=models.FloatField(blank=True, help_text='Wh, saved via eco/optimizations', null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='filter_usage',
            field=models.FloatField(blank=True, help_text='% of filter capacity used', null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='power_energy',
            field=models.FloatField(blank=True, help_text='Derived energy-cost figure reported by the API', null=True),
        ),
    ]
