# Generated by Django 6.0.6 on 2026-07-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioners', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='AirConditionerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('power', models.FloatField()),
                ('mode', models.CharField(max_length=30)),
                ('temperature', models.FloatField()),
                ('fan_speed', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('air_conditioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='monitoring.airconditioner')),
            ],
        ),
    ]
